version: '3.8'

services:
  web:
    build: .
    ports:
      - "127.0.0.1:5001:80"
    env_file:
      - .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - DATABASE_URL=postgresql://${NUXT_PRIVATE_DB_USER}:${NUXT_PRIVATE_DB_PASSWORD}@${NUXT_PRIVATE_DB_HOST}:${NUXT_PRIVATE_DB_PORT}/${NUXT_PRIVATE_DB_NAME}
      - JWT_SECRET=${NUXT_PRIVATE_JWT_SECRET}
    networks:
      - default
      - waro_runtime
      - postgresqlwarolabs_default

networks:
  waro_runtime:
    name: ${WARO_RUNTIME_NETWORK:-waro-network}
    external: true
  postgresqlwarolabs_default:
    external: true
