"""
Online Cart Router
PUBLIC endpoints for online ordering cart management (NO authentication required)
"""
from fastapi import APIRouter, Body, Depends, Query
from typing import List, Optional
from uuid import UUID
from pydantic import BaseModel, Field
from app.services import online_cart_service
from app.dependencies.customer_auth import get_current_customer
from app.models.online_cart import (
    OnlineCartItemCreate,
    DeliveryInfoUpdate,
    ModifierInput
)

router = APIRouter(prefix="/online/cart", tags=["Online Cart (Public)"])


class BatchCreateCartRequest(BaseModel):
    """Create cart with batch items - PUBLIC"""
    tenant_id: UUID  # Required for public endpoints
    items: List[OnlineCartItemCreate]
    session_id: Optional[str] = None
    order_type: str = Field(default='delivery', pattern='^(delivery|pickup|dine-in)$')


@router.post("/batch")
async def create_cart_batch(request: BatchCreateCartRequest):
    """
    Create cart and add all items in batch (PUBLIC - no auth).

    - tenant_id: Required - restaurant/tenant ID
    - session_id: Optional - for anonymous users (generated by frontend)
    - order_type: delivery|pickup|dine-in
    - items: Array of products with modifiers

    Returns created cart with all items.

    **Public endpoint - no authentication required**
    """
    return await online_cart_service.create_cart_with_batch_items(
        tenant_id=request.tenant_id,
        items=[item.dict() for item in request.items],
        session_id=request.session_id,
        order_type=request.order_type
    )


@router.get("/session/{session_id}")
async def get_cart_by_session(
    session_id: str,
    tenant_id: UUID = Query(..., description="Restaurant/Tenant ID")
):
    """
    Get active cart by session ID (PUBLIC - no auth).

    Use this to recover cart for anonymous users.

    **Public endpoint - no authentication required**
    """
    return await online_cart_service.get_cart_by_session(
        session_id=session_id,
        tenant_id=tenant_id
    )


@router.get("/{cart_id}")
async def get_cart(cart_id: UUID):
    """
    Get cart by ID (PUBLIC - no auth).

    **Public endpoint - no authentication required**
    """
    # TODO: Implement get_cart_by_id in service
    return {"success": True, "message": "Not implemented yet"}


@router.put("/{cart_id}/delivery")
async def update_delivery_info(
    cart_id: UUID,
    delivery_info: DeliveryInfoUpdate
):
    """
    Update delivery information for cart (PUBLIC - no auth).

    - order_type: delivery|pickup|dine-in
    - delivery_address_id: Optional - UUID of delivery address
    - scheduled_time: Optional - when to deliver/pickup
    - delivery_instructions: Optional - special instructions

    **Public endpoint - no authentication required**
    """
    return await online_cart_service.update_delivery_info(
        cart_id=cart_id,
        order_type=delivery_info.order_type,
        delivery_address_id=delivery_info.delivery_address_id,
        scheduled_time=delivery_info.scheduled_time if delivery_info.scheduled_time else None,
        delivery_instructions=delivery_info.delivery_instructions
    )


class AddItemRequest(BaseModel):
    """Add single item to cart"""
    product_id: UUID
    quantity: int = Field(gt=0)
    unit_price: float
    modifiers: List[ModifierInput] = []
    notes: Optional[str] = None


@router.post("/{cart_id}/items")
async def add_item_to_cart(
    cart_id: UUID,
    item: AddItemRequest
):
    """
    Add single item to existing cart (PUBLIC - no auth).

    **Public endpoint - no authentication required**
    """
    # TODO: Implement add_single_item in service
    return {"success": True, "message": "Not implemented yet - use batch endpoint"}


@router.delete("/{cart_id}/items/{item_id}")
async def delete_cart_item(
    cart_id: UUID,
    item_id: UUID
):
    """
    Delete item from cart (PUBLIC - no auth).

    Recalculates cart total automatically.

    **Public endpoint - no authentication required**
    """
    return await online_cart_service.delete_cart_item(
        cart_id=cart_id,
        item_id=item_id
    )


@router.delete("/{cart_id}")
async def clear_cart(cart_id: UUID):
    """
    Clear all items from cart (PUBLIC - no auth).

    **Public endpoint - no authentication required**
    """
    return await online_cart_service.clear_cart(cart_id=cart_id)


@router.put("/{cart_id}/customer/{customer_id}")
async def associate_customer(
    cart_id: UUID,
    customer_id: UUID
):
    """
    Associate customer to cart after verification (PUBLIC - no auth).

    Called after OTP verification to link cart to customer.

    **Public endpoint - no authentication required**
    """
    return await online_cart_service.associate_customer_to_cart(
        cart_id=cart_id,
        customer_id=customer_id
    )


@router.post("/{cart_id}/verify-with-session")
async def verify_cart_with_session(
    cart_id: UUID,
    current_customer: dict = Depends(get_current_customer),
):
    """
    Verify a cart using an existing waro_customer_session JWT cookie (no OTP required).

    Used when a returning customer auto-advances past the identity step.
    Sets is_verified = true and customer_id on the cart.
    Generates pickup_pin for pickup orders.

    Requires: waro_customer_session HttpOnly cookie
    Returns 404 if cart not found or not active.
    Returns 409 if cart is already linked to a different customer.
    """
    return await online_cart_service.verify_cart_with_session(
        cart_id=cart_id,
        customer_id=UUID(current_customer["customer_id"]),
        email=current_customer["email"],
    )


class CheckoutCartRequest(BaseModel):
    """
    Optional payment selection sent by the customer at checkout (warocol.com#610).

    Both fields are nullable in the schema but enforced in the service:
    `payment_method` (group slug) is required; `payment_method_id` is required
    only when the chosen group exposes nested methods. `triggersCartera`
    groups are rejected — anonymous customers cannot accrue cartera.
    """
    payment_method: Optional[str] = None
    payment_method_id: Optional[UUID] = None


@router.post("/{cart_id}/checkout")
async def checkout_cart(cart_id: UUID, body: Optional[CheckoutCartRequest] = None):
    """
    Finalize cart as a confirmed order (PUBLIC - no auth).

    Validates:
    - Cart is OTP-verified
    - Cart has items and meets minimum order amount
    - Delivery address is set when order_type is 'delivery'
    - payment_method (slug) is active for the tenant and not a cartera group
    - payment_method_id (when provided) belongs to the chosen group

    Returns order_number, total_amount, order_type, and pickup_pin (pickup orders only).

    Returns 409 if the cart was already checked out (double-submit prevention).

    **Public endpoint - no authentication required**
    """
    return await online_cart_service.checkout_cart(
        cart_id=cart_id,
        payment_method=body.payment_method if body else None,
        payment_method_id=body.payment_method_id if body else None,
    )
