"""
V1 Ordering Router
Cart, address, OTP, and customer-validate endpoints authenticated via API key.
tenant_id is injected from the API key context — never exposed to callers.
"""
from fastapi import APIRouter, Depends, Request, Response
from typing import List, Optional
from uuid import UUID
from pydantic import BaseModel, EmailStr, Field
from app.core.permissions import Module, require_module
from app.services import online_cart_service, address_profile_service, otp_service
from app.services.public_api_service import validate_api_key_auth
from app.services import public_restaurant_service
from app.models.online_cart import OnlineCartItemCreate, DeliveryInfoUpdate
from app.models.address_profile import AddressProfileCreate, AddressProfileUpdate
from app.core.security import create_customer_jwt, set_customer_cookie
from app.dependencies.customer_auth import get_customer_flexible

router = APIRouter(prefix="/v1/cart", tags=["V1 Ordering"])
address_router = APIRouter(prefix="/v1/addresses", tags=["V1 Addresses"])


class V1BatchCreateCartRequest(BaseModel):
    """Create cart with batch items — tenant_id injected from API key.
    session_id is always generated by the backend and returned in the response."""
    items: List[OnlineCartItemCreate]
    order_type: str = Field(default='delivery', pattern='^(delivery|pickup|dine-in)$')


@router.post("/batch", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def create_cart_batch(request: Request, body: V1BatchCreateCartRequest):
    """
    Create cart and add all items in batch.

    tenant_id is inferred from the API key — callers never need to provide it.

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    tenant_id, _ = validate_api_key_auth(request, "read")
    return await online_cart_service.create_cart_with_batch_items(
        tenant_id=UUID(tenant_id),
        items=[item.dict() for item in body.items],
        order_type=body.order_type,
    )


@router.get("/session/{session_id}", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def get_cart_by_session(session_id: str, request: Request):
    """
    Get active cart by session ID.

    tenant_id is inferred from the API key — no query param needed.

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    tenant_id, _ = validate_api_key_auth(request, "read")
    return await online_cart_service.get_cart_by_session(
        session_id=session_id,
        tenant_id=UUID(tenant_id),
    )


@router.put("/{cart_id}/delivery", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def update_delivery_info(cart_id: UUID, request: Request, delivery_info: DeliveryInfoUpdate):
    """
    Update delivery information for a cart.

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    return await online_cart_service.update_delivery_info(
        cart_id=cart_id,
        order_type=delivery_info.order_type,
        delivery_address_id=delivery_info.delivery_address_id,
        scheduled_time=delivery_info.scheduled_time if delivery_info.scheduled_time else None,
        delivery_instructions=delivery_info.delivery_instructions,
    )


@router.delete("/{cart_id}/items/{item_id}", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def delete_cart_item(cart_id: UUID, item_id: UUID, request: Request):
    """
    Delete a specific item from a cart.

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    return await online_cart_service.delete_cart_item(cart_id=cart_id, item_id=item_id)


@router.delete("/{cart_id}", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def clear_cart(cart_id: UUID, request: Request):
    """
    Clear all items from a cart.

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    return await online_cart_service.clear_cart(cart_id=cart_id)


@router.post("/{cart_id}/verify", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def verify_cart(
    cart_id: UUID,
    request: Request,
    current_customer: dict = Depends(get_customer_flexible),
):
    """
    Verify a cart using an existing customer session (no OTP required).

    Used for returning customers who already have a valid session.
    Accepts the customer JWT from either:
    - `X-Customer-Token: <jwt>` header (non-browser clients)
    - `waro_customer_session` cookie (browser clients)

    Sets is_verified = true and links the customer to the cart.
    Generates pickup_pin for pickup orders.

    **Authentication required:** API key + customer JWT
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    return await online_cart_service.verify_cart_with_session(
        cart_id=cart_id,
        customer_id=UUID(current_customer["customer_id"]),
        email=current_customer["email"],
    )


@router.post("/{cart_id}/checkout", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def checkout_cart_v1(cart_id: UUID, request: Request):
    """
    Finalize a verified cart as a confirmed order.

    The cart must have been previously verified via OTP (`/v1/otp/verify`)
    or session (`/v1/cart/{id}/verify`). No customer JWT required here —
    `is_verified` is already stored on the cart row.

    Returns order_number, total_amount, order_type, and pickup_pin (pickup orders).
    Returns 409 if the cart was already checked out (double-submit safe).

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    return await online_cart_service.checkout_cart(cart_id=cart_id)


# ---------------------------------------------------------------------------
# V1 Address endpoints
# ---------------------------------------------------------------------------


@address_router.post("", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def create_address(request: Request, address: AddressProfileCreate):
    """
    Create a new delivery address for a customer.

    Enforces a 5-address limit per customer. If `is_default=true`, all other
    addresses for this customer are unset as default.

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    return await address_profile_service.create_address(
        customer_id=address.customer_id,
        address_line1=address.address_line1,
        address_line2=address.address_line2,
        city=address.city,
        state=address.state,
        postal_code=address.postal_code,
        country=address.country,
        latitude=address.latitude,
        longitude=address.longitude,
        is_default=address.is_default,
        address_type=address.address_type,
        delivery_notes=address.delivery_notes,
    )


@address_router.get("/customer/{customer_id}", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def get_customer_addresses(customer_id: UUID, request: Request):
    """
    Get all addresses for a customer, ordered by default-first then newest.

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    return await address_profile_service.get_customer_addresses(customer_id)


@address_router.put("/{address_id}", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def update_address(
    address_id: UUID,
    customer_id: UUID,
    request: Request,
    address_update: AddressProfileUpdate,
):
    """
    Update an existing address (partial update — only provided fields are changed).

    - **customer_id**: Query param for ownership validation
    - **address_id**: Path param identifying the address

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    update_data = address_update.model_dump(exclude_none=True)
    return await address_profile_service.update_address(
        address_id=address_id,
        customer_id=customer_id,
        update_data=update_data,
    )


@address_router.delete("/{address_id}", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def delete_address(address_id: UUID, customer_id: UUID, request: Request):
    """
    Delete an address. If the deleted address was the default and others exist,
    the most recent address is automatically promoted to default.

    - **customer_id**: Query param for ownership validation

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    return await address_profile_service.delete_address(address_id, customer_id)


@address_router.patch("/{address_id}/set-default", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def set_default_address(address_id: UUID, customer_id: UUID, request: Request):
    """
    Set an address as the customer's default. Unsets all other addresses as default.

    - **customer_id**: Query param for ownership validation

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    return await address_profile_service.set_default_address(address_id, customer_id)


# ---------------------------------------------------------------------------
# V1 OTP endpoints
# ---------------------------------------------------------------------------

otp_router = APIRouter(prefix="/v1/otp", tags=["V1 OTP"])


class V1SendOTPRequest(BaseModel):
    email: EmailStr
    cart_id: Optional[UUID] = None


class V1VerifyOTPRequest(BaseModel):
    email: EmailStr
    cart_id: Optional[UUID] = None
    otp_code: str


class V1ResendOTPRequest(BaseModel):
    email: EmailStr
    cart_id: Optional[UUID] = None


@otp_router.post("/send", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def v1_send_otp(request: Request, body: V1SendOTPRequest):
    """
    Send OTP code via email.

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    return await otp_service.send_otp_email(email=body.email, cart_id=body.cart_id)


@otp_router.post("/verify", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def v1_verify_otp(request: Request, body: V1VerifyOTPRequest, response: Response):
    """
    Verify OTP code.

    In addition to setting the `waro_customer_session` HttpOnly cookie (browser clients),
    the response body includes a `customer_token` field — the same JWT — so that
    non-browser clients (CLI, mobile, server-side) can store it and send it as an
    `X-Customer-Token` header in subsequent requests.

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    result = await otp_service.verify_otp_code(
        email=body.email,
        cart_id=body.cart_id,
        otp_code=body.otp_code,
    )
    if result.get("success") and result.get("customer_id"):
        jwt_token = create_customer_jwt(
            customer_id=result["customer_id"],
            email=body.email,
        )
        set_customer_cookie(response, jwt_token)
        result["customer_token"] = jwt_token
    return result


@otp_router.post("/resend", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def v1_resend_otp(request: Request, body: V1ResendOTPRequest):
    """
    Resend OTP code. Cooldown: 60 seconds between resends.

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    validate_api_key_auth(request, "read")
    return await otp_service.send_otp_email(email=body.email, cart_id=body.cart_id)


# ---------------------------------------------------------------------------
# V1 Customer validate endpoint
# ---------------------------------------------------------------------------

customer_router_v1 = APIRouter(prefix="/v1/customer", tags=["V1 Customer"])

# ---------------------------------------------------------------------------
# V1 Product detail endpoint
# ---------------------------------------------------------------------------

product_router_v1 = APIRouter(prefix="/v1/product", tags=["V1 Product"])


class V1ValidateCustomerRequest(BaseModel):
    phone_number: str
    cart_total: float = 0.0


@customer_router_v1.post("/validate", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def v1_validate_customer(request: Request, body: V1ValidateCustomerRequest):
    """
    Validate customer eligibility to place an order.

    Checks blacklist status, customer tier, and spending limits.

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    tenant_id, _ = validate_api_key_auth(request, "read")
    return await otp_service.validate_customer(
        phone_number=body.phone_number,
        cart_total=body.cart_total,
        tenant_id=UUID(tenant_id),
    )


@product_router_v1.get("/{product_id}", dependencies=[Depends(require_module(Module.INTEGRACIONES))])
async def v1_get_product_detail(product_id: UUID, request: Request):
    """
    Get full product details including modifier groups.

    Use this after `GET /v1/menu` — when a product has `has_modifiers: true`,
    fetch this endpoint to get the selectable modifier groups before adding
    the item to the cart.

    **Response includes:**
    - Product name, description, price, category
    - `modifier_groups[]` — each group has `is_required`, `min_qty`, `max_qty`,
      and `modifiers[]` with `id`, `name`, `price`, `is_default`
    - `is_available_online` — false means the product is currently unavailable online

    **Authentication required:** `Authorization: Bearer waro_sk_xxx` or `X-API-Key: waro_sk_xxx`
    **Scope required:** `read`
    """
    tenant_id, _ = validate_api_key_auth(request, "read")
    product = await public_restaurant_service.get_product_detail_by_tenant_id(
        tenant_id=UUID(tenant_id),
        product_id=product_id,
    )
    return {"success": True, "data": product}
