-- warocol.com#2309: wide city/town lists for Negocio countries (skip CO).
-- Additive only. UNIQUE(city_slug). New extra-country slugs use {slug}-{cc}.
-- Do not rebuild Colombia. Existing AR/MX/US short-list rows stay (ON CONFLICT DO NOTHING).

INSERT INTO public_cities (
  country, country_code, city, city_slug, is_active, sort_order
) VALUES
  ('Panama', 'PA', 'Panama City', 'panama-city-pa', true, 10),
  ('Panama', 'PA', 'San Miguelito', 'san-miguelito-pa', true, 20),
  ('Panama', 'PA', 'Tocumen', 'tocumen-pa', true, 30),
  ('Panama', 'PA', 'Arraijan', 'arraijan-pa', true, 40),
  ('Panama', 'PA', 'La Chorrera', 'la-chorrera-pa', true, 50),
  ('Panama', 'PA', 'David', 'david-pa', true, 60),
  ('Panama', 'PA', 'Colon', 'colon-pa', true, 70),
  ('Panama', 'PA', 'Santiago', 'santiago-pa', true, 80),
  ('Panama', 'PA', 'Chitre', 'chitre-pa', true, 90),
  ('Panama', 'PA', 'Penonome', 'penonome-pa', true, 100),
  ('Panama', 'PA', 'Las Tablas', 'las-tablas-pa', true, 110),
  ('Panama', 'PA', 'Aguadulce', 'aguadulce-pa', true, 120),
  ('Panama', 'PA', 'Changuinola', 'changuinola-pa', true, 130),
  ('Panama', 'PA', 'Puerto Armuelles', 'puerto-armuelles-pa', true, 140),
  ('Panama', 'PA', 'La Palma', 'la-palma-pa', true, 150),
  ('Panama', 'PA', 'Bocas del Toro', 'bocas-del-toro-pa', true, 160),
  ('Panama', 'PA', 'Volcan', 'volcan-pa', true, 170),
  ('Panama', 'PA', 'Boquete', 'boquete-pa', true, 180),
  ('Panama', 'PA', 'Anton', 'anton-pa', true, 190),
  ('Panama', 'PA', 'Capira', 'capira-pa', true, 200),
  ('Panama', 'PA', 'Chepo', 'chepo-pa', true, 210),
  ('Panama', 'PA', 'Pacora', 'pacora-pa', true, 220),
  ('Panama', 'PA', 'Juan Diaz', 'juan-diaz-pa', true, 230),
  ('Panama', 'PA', 'Alcalde Diaz', 'alcalde-diaz-pa', true, 240),
  ('Panama', 'PA', 'Vista Alegre', 'vista-alegre-pa', true, 250),
  ('Panama', 'PA', 'Nuevo Chorrillo', 'nuevo-chorrillo-pa', true, 260),
  ('Panama', 'PA', 'Veracruz', 'veracruz-pa', true, 270),
  ('Panama', 'PA', 'Chame', 'chame-pa', true, 280),
  ('Panama', 'PA', 'Sora', 'sora-pa', true, 290),
  ('Panama', 'PA', 'El Coco', 'el-coco-pa', true, 300),
  ('Panama', 'PA', 'Ocu', 'ocu-pa', true, 310),
  ('Panama', 'PA', 'Los Santos', 'los-santos-pa', true, 320),
  ('Panama', 'PA', 'Guarare', 'guarare-pa', true, 330),
  ('Panama', 'PA', 'Pedasi', 'pedasi-pa', true, 340),
  ('Panama', 'PA', 'Tonosi', 'tonosi-pa', true, 350),
  ('Panama', 'PA', 'Sona', 'sona-pa', true, 360),
  ('Panama', 'PA', 'La Villa de Los Santos', 'la-villa-de-los-santos-pa', true, 370),
  ('Panama', 'PA', 'Rio Hato', 'rio-hato-pa', true, 380),
  ('Panama', 'PA', 'Coronado', 'coronado-pa', true, 390),
  ('Panama', 'PA', 'Gamboa', 'gamboa-pa', true, 400),
  ('Chile', 'CL', 'Santiago', 'santiago-cl', true, 10),
  ('Chile', 'CL', 'Puente Alto', 'puente-alto-cl', true, 20),
  ('Chile', 'CL', 'Maipu', 'maipu-cl', true, 30),
  ('Chile', 'CL', 'La Florida', 'la-florida-cl', true, 40),
  ('Chile', 'CL', 'Antofagasta', 'antofagasta-cl', true, 50),
  ('Chile', 'CL', 'Vina del Mar', 'vina-del-mar-cl', true, 60),
  ('Chile', 'CL', 'Valparaiso', 'valparaiso-cl', true, 70),
  ('Chile', 'CL', 'Temuco', 'temuco-cl', true, 80),
  ('Chile', 'CL', 'San Bernardo', 'san-bernardo-cl', true, 90),
  ('Chile', 'CL', 'Concepcion', 'concepcion-cl', true, 100),
  ('Chile', 'CL', 'Rancagua', 'rancagua-cl', true, 110),
  ('Chile', 'CL', 'Talca', 'talca-cl', true, 120),
  ('Chile', 'CL', 'Arica', 'arica-cl', true, 130),
  ('Chile', 'CL', 'Chillan', 'chillan-cl', true, 140),
  ('Chile', 'CL', 'Iquique', 'iquique-cl', true, 150),
  ('Chile', 'CL', 'Los Angeles', 'los-angeles-cl', true, 160),
  ('Chile', 'CL', 'Puerto Montt', 'puerto-montt-cl', true, 170),
  ('Chile', 'CL', 'Coquimbo', 'coquimbo-cl', true, 180),
  ('Chile', 'CL', 'La Serena', 'la-serena-cl', true, 190),
  ('Chile', 'CL', 'Osorno', 'osorno-cl', true, 200),
  ('Chile', 'CL', 'Valdivia', 'valdivia-cl', true, 210),
  ('Chile', 'CL', 'Quilpue', 'quilpue-cl', true, 220),
  ('Chile', 'CL', 'Calama', 'calama-cl', true, 230),
  ('Chile', 'CL', 'Copiapo', 'copiapo-cl', true, 240),
  ('Chile', 'CL', 'Punta Arenas', 'punta-arenas-cl', true, 250),
  ('Chile', 'CL', 'Quillota', 'quillota-cl', true, 260),
  ('Chile', 'CL', 'Curico', 'curico-cl', true, 270),
  ('Chile', 'CL', 'Linares', 'linares-cl', true, 280),
  ('Chile', 'CL', 'Melipilla', 'melipilla-cl', true, 290),
  ('Chile', 'CL', 'San Antonio', 'san-antonio-cl', true, 300),
  ('Chile', 'CL', 'Coronel', 'coronel-cl', true, 310),
  ('Chile', 'CL', 'Talcahuano', 'talcahuano-cl', true, 320),
  ('Chile', 'CL', 'Villa Alemana', 'villa-alemana-cl', true, 330),
  ('Chile', 'CL', 'Ovalle', 'ovalle-cl', true, 340),
  ('Chile', 'CL', 'Los Andes', 'los-andes-cl', true, 350),
  ('Chile', 'CL', 'San Felipe', 'san-felipe-cl', true, 360),
  ('Chile', 'CL', 'Castro', 'castro-cl', true, 370),
  ('Chile', 'CL', 'Ancud', 'ancud-cl', true, 380),
  ('Chile', 'CL', 'Puerto Varas', 'puerto-varas-cl', true, 390),
  ('Chile', 'CL', 'Coyhaique', 'coyhaique-cl', true, 400),
  ('United States', 'US', 'Miami', 'miami-us', true, 10),
  ('United States', 'US', 'New York', 'new-york-us', true, 20),
  ('United States', 'US', 'Houston', 'houston-us', true, 30),
  ('United States', 'US', 'Los Angeles', 'los-angeles-us', true, 40),
  ('United States', 'US', 'Chicago', 'chicago-us', true, 50),
  ('United States', 'US', 'Dallas', 'dallas-us', true, 60),
  ('United States', 'US', 'Atlanta', 'atlanta-us', true, 70),
  ('United States', 'US', 'Phoenix', 'phoenix-us', true, 80),
  ('United States', 'US', 'Philadelphia', 'philadelphia-us', true, 90),
  ('United States', 'US', 'San Antonio', 'san-antonio-us', true, 100),
  ('United States', 'US', 'San Diego', 'san-diego-us', true, 110),
  ('United States', 'US', 'San Jose', 'san-jose-us', true, 120),
  ('United States', 'US', 'Austin', 'austin-us', true, 130),
  ('United States', 'US', 'Jacksonville', 'jacksonville-us', true, 140),
  ('United States', 'US', 'Fort Worth', 'fort-worth-us', true, 150),
  ('United States', 'US', 'Columbus', 'columbus-us', true, 160),
  ('United States', 'US', 'Charlotte', 'charlotte-us', true, 170),
  ('United States', 'US', 'Indianapolis', 'indianapolis-us', true, 180),
  ('United States', 'US', 'Seattle', 'seattle-us', true, 190),
  ('United States', 'US', 'Denver', 'denver-us', true, 200),
  ('United States', 'US', 'Washington', 'washington-us', true, 210),
  ('United States', 'US', 'Boston', 'boston-us', true, 220),
  ('United States', 'US', 'Nashville', 'nashville-us', true, 230),
  ('United States', 'US', 'Detroit', 'detroit-us', true, 240),
  ('United States', 'US', 'Oklahoma City', 'oklahoma-city-us', true, 250),
  ('United States', 'US', 'Portland', 'portland-us', true, 260),
  ('United States', 'US', 'Las Vegas', 'las-vegas-us', true, 270),
  ('United States', 'US', 'Memphis', 'memphis-us', true, 280),
  ('United States', 'US', 'Louisville', 'louisville-us', true, 290),
  ('United States', 'US', 'Baltimore', 'baltimore-us', true, 300),
  ('United States', 'US', 'Milwaukee', 'milwaukee-us', true, 310),
  ('United States', 'US', 'Albuquerque', 'albuquerque-us', true, 320),
  ('United States', 'US', 'Tucson', 'tucson-us', true, 330),
  ('United States', 'US', 'Fresno', 'fresno-us', true, 340),
  ('United States', 'US', 'Sacramento', 'sacramento-us', true, 350),
  ('United States', 'US', 'Kansas City', 'kansas-city-us', true, 360),
  ('United States', 'US', 'Mesa', 'mesa-us', true, 370),
  ('United States', 'US', 'Orlando', 'orlando-us', true, 380),
  ('United States', 'US', 'Tampa', 'tampa-us', true, 390),
  ('United States', 'US', 'Raleigh', 'raleigh-us', true, 400),
  ('United States', 'US', 'Cleveland', 'cleveland-us', true, 410),
  ('United States', 'US', 'Pittsburgh', 'pittsburgh-us', true, 420),
  ('United States', 'US', 'Cincinnati', 'cincinnati-us', true, 430),
  ('United States', 'US', 'Minneapolis', 'minneapolis-us', true, 440),
  ('United States', 'US', 'New Orleans', 'new-orleans-us', true, 450),
  ('United States', 'US', 'Salt Lake City', 'salt-lake-city-us', true, 460),
  ('United States', 'US', 'Honolulu', 'honolulu-us', true, 470),
  ('United States', 'US', 'Anchorage', 'anchorage-us', true, 480),
  ('Canada', 'CA', 'Toronto', 'toronto-ca', true, 10),
  ('Canada', 'CA', 'Montreal', 'montreal-ca', true, 20),
  ('Canada', 'CA', 'Vancouver', 'vancouver-ca', true, 30),
  ('Canada', 'CA', 'Calgary', 'calgary-ca', true, 40),
  ('Canada', 'CA', 'Edmonton', 'edmonton-ca', true, 50),
  ('Canada', 'CA', 'Ottawa', 'ottawa-ca', true, 60),
  ('Canada', 'CA', 'Winnipeg', 'winnipeg-ca', true, 70),
  ('Canada', 'CA', 'Quebec City', 'quebec-city-ca', true, 80),
  ('Canada', 'CA', 'Hamilton', 'hamilton-ca', true, 90),
  ('Canada', 'CA', 'Kitchener', 'kitchener-ca', true, 100),
  ('Canada', 'CA', 'London', 'london-ca', true, 110),
  ('Canada', 'CA', 'Victoria', 'victoria-ca', true, 120),
  ('Canada', 'CA', 'Halifax', 'halifax-ca', true, 130),
  ('Canada', 'CA', 'Oshawa', 'oshawa-ca', true, 140),
  ('Canada', 'CA', 'Windsor', 'windsor-ca', true, 150),
  ('Canada', 'CA', 'Saskatoon', 'saskatoon-ca', true, 160),
  ('Canada', 'CA', 'Regina', 'regina-ca', true, 170),
  ('Canada', 'CA', 'St Johns', 'st-johns-ca', true, 180),
  ('Canada', 'CA', 'Barrie', 'barrie-ca', true, 190),
  ('Canada', 'CA', 'Kelowna', 'kelowna-ca', true, 200),
  ('Canada', 'CA', 'Abbotsford', 'abbotsford-ca', true, 210),
  ('Canada', 'CA', 'Sherbrooke', 'sherbrooke-ca', true, 220),
  ('Canada', 'CA', 'Guelph', 'guelph-ca', true, 230),
  ('Canada', 'CA', 'Kingston', 'kingston-ca', true, 240),
  ('Canada', 'CA', 'Kanata', 'kanata-ca', true, 250),
  ('Canada', 'CA', 'Moncton', 'moncton-ca', true, 260),
  ('Canada', 'CA', 'Thunder Bay', 'thunder-bay-ca', true, 270),
  ('Canada', 'CA', 'Saint John', 'saint-john-ca', true, 280),
  ('Canada', 'CA', 'Brantford', 'brantford-ca', true, 290),
  ('Canada', 'CA', 'Nanaimo', 'nanaimo-ca', true, 300),
  ('Canada', 'CA', 'Lethbridge', 'lethbridge-ca', true, 310),
  ('Canada', 'CA', 'Sudbury', 'sudbury-ca', true, 320),
  ('Canada', 'CA', 'Red Deer', 'red-deer-ca', true, 330),
  ('Canada', 'CA', 'Kamloops', 'kamloops-ca', true, 340),
  ('Canada', 'CA', 'Chilliwack', 'chilliwack-ca', true, 350),
  ('Canada', 'CA', 'Niagara Falls', 'niagara-falls-ca', true, 360),
  ('Canada', 'CA', 'Peterborough', 'peterborough-ca', true, 370),
  ('Canada', 'CA', 'Sault Ste Marie', 'sault-ste-marie-ca', true, 380),
  ('Canada', 'CA', 'Prince George', 'prince-george-ca', true, 390),
  ('Canada', 'CA', 'Trois-Rivieres', 'trois-rivieres-ca', true, 400),
  ('Dominican Republic', 'DO', 'Santo Domingo', 'santo-domingo-do', true, 10),
  ('Dominican Republic', 'DO', 'Santiago', 'santiago-do', true, 20),
  ('Dominican Republic', 'DO', 'La Romana', 'la-romana-do', true, 30),
  ('Dominican Republic', 'DO', 'San Pedro de Macoris', 'san-pedro-de-macoris-do', true, 40),
  ('Dominican Republic', 'DO', 'San Francisco de Macoris', 'san-francisco-de-macoris-do', true, 50),
  ('Dominican Republic', 'DO', 'Puerto Plata', 'puerto-plata-do', true, 60),
  ('Dominican Republic', 'DO', 'La Vega', 'la-vega-do', true, 70),
  ('Dominican Republic', 'DO', 'San Cristobal', 'san-cristobal-do', true, 80),
  ('Dominican Republic', 'DO', 'Higüey', 'higuey-do', true, 90),
  ('Dominican Republic', 'DO', 'Bonao', 'bonao-do', true, 100),
  ('Dominican Republic', 'DO', 'Moca', 'moca-do', true, 110),
  ('Dominican Republic', 'DO', 'Bani', 'bani-do', true, 120),
  ('Dominican Republic', 'DO', 'Azua', 'azua-do', true, 130),
  ('Dominican Republic', 'DO', 'Mao', 'mao-do', true, 140),
  ('Dominican Republic', 'DO', 'Cotui', 'cotui-do', true, 150),
  ('Dominican Republic', 'DO', 'Esperanza', 'esperanza-do', true, 160),
  ('Dominican Republic', 'DO', 'Hato Mayor', 'hato-mayor-do', true, 170),
  ('Dominican Republic', 'DO', 'Nagua', 'nagua-do', true, 180),
  ('Dominican Republic', 'DO', 'Barahona', 'barahona-do', true, 190),
  ('Dominican Republic', 'DO', 'Monte Cristi', 'monte-cristi-do', true, 200),
  ('Dominican Republic', 'DO', 'Dajabon', 'dajabon-do', true, 210),
  ('Dominican Republic', 'DO', 'Samana', 'samana-do', true, 220),
  ('Dominican Republic', 'DO', 'Jarabacoa', 'jarabacoa-do', true, 230),
  ('Dominican Republic', 'DO', 'Constanza', 'constanza-do', true, 240),
  ('Dominican Republic', 'DO', 'Bavaro', 'bavaro-do', true, 250),
  ('Dominican Republic', 'DO', 'Punta Cana', 'punta-cana-do', true, 260),
  ('Dominican Republic', 'DO', 'Sosua', 'sosua-do', true, 270),
  ('Dominican Republic', 'DO', 'Cabarete', 'cabarete-do', true, 280),
  ('Dominican Republic', 'DO', 'San Juan de la Maguana', 'san-juan-de-la-maguana-do', true, 290),
  ('Dominican Republic', 'DO', 'Neiba', 'neiba-do', true, 300),
  ('Dominican Republic', 'DO', 'Pedernales', 'pedernales-do', true, 310),
  ('Dominican Republic', 'DO', 'El Seibo', 'el-seibo-do', true, 320),
  ('Dominican Republic', 'DO', 'Monte Plata', 'monte-plata-do', true, 330),
  ('Dominican Republic', 'DO', 'Villa Altagracia', 'villa-altagracia-do', true, 340),
  ('Dominican Republic', 'DO', 'Tamboril', 'tamboril-do', true, 350),
  ('Dominican Republic', 'DO', 'Villa Gonzalez', 'villa-gonzalez-do', true, 360),
  ('Dominican Republic', 'DO', 'Navarrete', 'navarrete-do', true, 370),
  ('Dominican Republic', 'DO', 'Las Terrenas', 'las-terrenas-do', true, 380),
  ('Dominican Republic', 'DO', 'Bayahibe', 'bayahibe-do', true, 390),
  ('Dominican Republic', 'DO', 'Boca Chica', 'boca-chica-do', true, 400),
  ('Uruguay', 'UY', 'Montevideo', 'montevideo-uy', true, 10),
  ('Uruguay', 'UY', 'Salto', 'salto-uy', true, 20),
  ('Uruguay', 'UY', 'Ciudad de la Costa', 'ciudad-de-la-costa-uy', true, 30),
  ('Uruguay', 'UY', 'Paysandu', 'paysandu-uy', true, 40),
  ('Uruguay', 'UY', 'Las Piedras', 'las-piedras-uy', true, 50),
  ('Uruguay', 'UY', 'Rivera', 'rivera-uy', true, 60),
  ('Uruguay', 'UY', 'Maldonado', 'maldonado-uy', true, 70),
  ('Uruguay', 'UY', 'Tacuarembo', 'tacuarembo-uy', true, 80),
  ('Uruguay', 'UY', 'Melo', 'melo-uy', true, 90),
  ('Uruguay', 'UY', 'Mercedes', 'mercedes-uy', true, 100),
  ('Uruguay', 'UY', 'Artigas', 'artigas-uy', true, 110),
  ('Uruguay', 'UY', 'Minas', 'minas-uy', true, 120),
  ('Uruguay', 'UY', 'San Jose de Mayo', 'san-jose-de-mayo-uy', true, 130),
  ('Uruguay', 'UY', 'Durazno', 'durazno-uy', true, 140),
  ('Uruguay', 'UY', 'Florida', 'florida-uy', true, 150),
  ('Uruguay', 'UY', 'Barros Blancos', 'barros-blancos-uy', true, 160),
  ('Uruguay', 'UY', 'Ciudad del Plata', 'ciudad-del-plata-uy', true, 170),
  ('Uruguay', 'UY', 'San Carlos', 'san-carlos-uy', true, 180),
  ('Uruguay', 'UY', 'Colonia del Sacramento', 'colonia-del-sacramento-uy', true, 190),
  ('Uruguay', 'UY', 'Pando', 'pando-uy', true, 200),
  ('Uruguay', 'UY', 'Treinta y Tres', 'treinta-y-tres-uy', true, 210),
  ('Uruguay', 'UY', 'Rocha', 'rocha-uy', true, 220),
  ('Uruguay', 'UY', 'Fray Bentos', 'fray-bentos-uy', true, 230),
  ('Uruguay', 'UY', 'Trinidad', 'trinidad-uy', true, 240),
  ('Uruguay', 'UY', 'La Paz', 'la-paz-uy', true, 250),
  ('Uruguay', 'UY', 'Canelones', 'canelones-uy', true, 260),
  ('Uruguay', 'UY', 'Delta del Tigre', 'delta-del-tigre-uy', true, 270),
  ('Uruguay', 'UY', 'Young', 'young-uy', true, 280),
  ('Uruguay', 'UY', 'Dolores', 'dolores-uy', true, 290),
  ('Uruguay', 'UY', 'Carmelo', 'carmelo-uy', true, 300),
  ('Uruguay', 'UY', 'Nueva Helvecia', 'nueva-helvecia-uy', true, 310),
  ('Uruguay', 'UY', 'Punta del Este', 'punta-del-este-uy', true, 320),
  ('Uruguay', 'UY', 'Piriapolis', 'piriapolis-uy', true, 330),
  ('Uruguay', 'UY', 'Atlántida', 'atlantida-uy', true, 340),
  ('Uruguay', 'UY', 'Parque del Plata', 'parque-del-plata-uy', true, 350),
  ('Uruguay', 'UY', 'Progreso', 'progreso-uy', true, 360),
  ('Uruguay', 'UY', 'Toledo', 'toledo-uy', true, 370),
  ('Uruguay', 'UY', 'Sauce', 'sauce-uy', true, 380),
  ('Uruguay', 'UY', 'Sarandi del Yi', 'sarandi-del-yi-uy', true, 390),
  ('Uruguay', 'UY', 'Paso de los Toros', 'paso-de-los-toros-uy', true, 400),
  ('Australia', 'AU', 'Sydney', 'sydney-au', true, 10),
  ('Australia', 'AU', 'Melbourne', 'melbourne-au', true, 20),
  ('Australia', 'AU', 'Brisbane', 'brisbane-au', true, 30),
  ('Australia', 'AU', 'Perth', 'perth-au', true, 40),
  ('Australia', 'AU', 'Adelaide', 'adelaide-au', true, 50),
  ('Australia', 'AU', 'Gold Coast', 'gold-coast-au', true, 60),
  ('Australia', 'AU', 'Canberra', 'canberra-au', true, 70),
  ('Australia', 'AU', 'Newcastle', 'newcastle-au', true, 80),
  ('Australia', 'AU', 'Wollongong', 'wollongong-au', true, 90),
  ('Australia', 'AU', 'Logan City', 'logan-city-au', true, 100),
  ('Australia', 'AU', 'Geelong', 'geelong-au', true, 110),
  ('Australia', 'AU', 'Hobart', 'hobart-au', true, 120),
  ('Australia', 'AU', 'Townsville', 'townsville-au', true, 130),
  ('Australia', 'AU', 'Cairns', 'cairns-au', true, 140),
  ('Australia', 'AU', 'Toowoomba', 'toowoomba-au', true, 150),
  ('Australia', 'AU', 'Darwin', 'darwin-au', true, 160),
  ('Australia', 'AU', 'Ballarat', 'ballarat-au', true, 170),
  ('Australia', 'AU', 'Bendigo', 'bendigo-au', true, 180),
  ('Australia', 'AU', 'Albury', 'albury-au', true, 190),
  ('Australia', 'AU', 'Launceston', 'launceston-au', true, 200),
  ('Australia', 'AU', 'Mackay', 'mackay-au', true, 210),
  ('Australia', 'AU', 'Rockhampton', 'rockhampton-au', true, 220),
  ('Australia', 'AU', 'Bunbury', 'bunbury-au', true, 230),
  ('Australia', 'AU', 'Bundaberg', 'bundaberg-au', true, 240),
  ('Australia', 'AU', 'Coffs Harbour', 'coffs-harbour-au', true, 250),
  ('Australia', 'AU', 'Wagga Wagga', 'wagga-wagga-au', true, 260),
  ('Australia', 'AU', 'Hervey Bay', 'hervey-bay-au', true, 270),
  ('Australia', 'AU', 'Mildura', 'mildura-au', true, 280),
  ('Australia', 'AU', 'Shepparton', 'shepparton-au', true, 290),
  ('Australia', 'AU', 'Port Macquarie', 'port-macquarie-au', true, 300),
  ('Australia', 'AU', 'Gladstone', 'gladstone-au', true, 310),
  ('Australia', 'AU', 'Tamworth', 'tamworth-au', true, 320),
  ('Australia', 'AU', 'Traralgon', 'traralgon-au', true, 330),
  ('Australia', 'AU', 'Orange', 'orange-au', true, 340),
  ('Australia', 'AU', 'Dubbo', 'dubbo-au', true, 350),
  ('Australia', 'AU', 'Geraldton', 'geraldton-au', true, 360),
  ('Australia', 'AU', 'Kalgoorlie', 'kalgoorlie-au', true, 370),
  ('Australia', 'AU', 'Nowra', 'nowra-au', true, 380),
  ('Australia', 'AU', 'Warrnambool', 'warrnambool-au', true, 390),
  ('Australia', 'AU', 'Albany', 'albany-au', true, 400),
  ('New Zealand', 'NZ', 'Auckland', 'auckland-nz', true, 10),
  ('New Zealand', 'NZ', 'Wellington', 'wellington-nz', true, 20),
  ('New Zealand', 'NZ', 'Christchurch', 'christchurch-nz', true, 30),
  ('New Zealand', 'NZ', 'Hamilton', 'hamilton-nz', true, 40),
  ('New Zealand', 'NZ', 'Tauranga', 'tauranga-nz', true, 50),
  ('New Zealand', 'NZ', 'Napier-Hastings', 'napier-hastings-nz', true, 60),
  ('New Zealand', 'NZ', 'Dunedin', 'dunedin-nz', true, 70),
  ('New Zealand', 'NZ', 'Palmerston North', 'palmerston-north-nz', true, 80),
  ('New Zealand', 'NZ', 'Nelson', 'nelson-nz', true, 90),
  ('New Zealand', 'NZ', 'Rotorua', 'rotorua-nz', true, 100),
  ('New Zealand', 'NZ', 'New Plymouth', 'new-plymouth-nz', true, 110),
  ('New Zealand', 'NZ', 'Whangarei', 'whangarei-nz', true, 120),
  ('New Zealand', 'NZ', 'Invercargill', 'invercargill-nz', true, 130),
  ('New Zealand', 'NZ', 'Whanganui', 'whanganui-nz', true, 140),
  ('New Zealand', 'NZ', 'Gisborne', 'gisborne-nz', true, 150),
  ('New Zealand', 'NZ', 'Blenheim', 'blenheim-nz', true, 160),
  ('New Zealand', 'NZ', 'Pukekohe', 'pukekohe-nz', true, 170),
  ('New Zealand', 'NZ', 'Timaru', 'timaru-nz', true, 180),
  ('New Zealand', 'NZ', 'Taupo', 'taupo-nz', true, 190),
  ('New Zealand', 'NZ', 'Masterton', 'masterton-nz', true, 200),
  ('New Zealand', 'NZ', 'Levin', 'levin-nz', true, 210),
  ('New Zealand', 'NZ', 'Whakatane', 'whakatane-nz', true, 220),
  ('New Zealand', 'NZ', 'Cambridge', 'cambridge-nz', true, 230),
  ('New Zealand', 'NZ', 'Feilding', 'feilding-nz', true, 240),
  ('New Zealand', 'NZ', 'Ashburton', 'ashburton-nz', true, 250),
  ('New Zealand', 'NZ', 'Rangiora', 'rangiora-nz', true, 260),
  ('New Zealand', 'NZ', 'Queenstown', 'queenstown-nz', true, 270),
  ('New Zealand', 'NZ', 'Oamaru', 'oamaru-nz', true, 280),
  ('New Zealand', 'NZ', 'Hawera', 'hawera-nz', true, 290),
  ('New Zealand', 'NZ', 'Gore', 'gore-nz', true, 300),
  ('New Zealand', 'NZ', 'Greymouth', 'greymouth-nz', true, 310),
  ('New Zealand', 'NZ', 'Westport', 'westport-nz', true, 320),
  ('New Zealand', 'NZ', 'Kaikoura', 'kaikoura-nz', true, 330),
  ('New Zealand', 'NZ', 'Kerikeri', 'kerikeri-nz', true, 340),
  ('New Zealand', 'NZ', 'Thames', 'thames-nz', true, 350),
  ('New Zealand', 'NZ', 'Taumarunui', 'taumarunui-nz', true, 360),
  ('New Zealand', 'NZ', 'Te Awamutu', 'te-awamutu-nz', true, 370),
  ('New Zealand', 'NZ', 'Porirua', 'porirua-nz', true, 380),
  ('New Zealand', 'NZ', 'Lower Hutt', 'lower-hutt-nz', true, 390),
  ('New Zealand', 'NZ', 'Upper Hutt', 'upper-hutt-nz', true, 400),
  ('Singapore', 'SG', 'Singapore', 'singapore-sg', true, 10),
  ('Singapore', 'SG', 'Jurong East', 'jurong-east-sg', true, 20),
  ('Singapore', 'SG', 'Woodlands', 'woodlands-sg', true, 30),
  ('Singapore', 'SG', 'Tampines', 'tampines-sg', true, 40),
  ('Singapore', 'SG', 'Sengkang', 'sengkang-sg', true, 50),
  ('Singapore', 'SG', 'Hougang', 'hougang-sg', true, 60),
  ('Singapore', 'SG', 'Yishun', 'yishun-sg', true, 70),
  ('Singapore', 'SG', 'Bedok', 'bedok-sg', true, 80),
  ('Singapore', 'SG', 'Punggol', 'punggol-sg', true, 90),
  ('Singapore', 'SG', 'Ang Mo Kio', 'ang-mo-kio-sg', true, 100),
  ('Singapore', 'SG', 'Bukit Merah', 'bukit-merah-sg', true, 110),
  ('Singapore', 'SG', 'Choa Chu Kang', 'choa-chu-kang-sg', true, 120),
  ('Singapore', 'SG', 'Bukit Batok', 'bukit-batok-sg', true, 130),
  ('Singapore', 'SG', 'Pasir Ris', 'pasir-ris-sg', true, 140),
  ('Singapore', 'SG', 'Toa Payoh', 'toa-payoh-sg', true, 150),
  ('Singapore', 'SG', 'Queenstown', 'queenstown-sg', true, 160),
  ('Singapore', 'SG', 'Clementi', 'clementi-sg', true, 170),
  ('Singapore', 'SG', 'Geylang', 'geylang-sg', true, 180),
  ('Singapore', 'SG', 'Kallang', 'kallang-sg', true, 190),
  ('Singapore', 'SG', 'Novena', 'novena-sg', true, 200),
  ('Singapore', 'SG', 'Serangoon', 'serangoon-sg', true, 210),
  ('Singapore', 'SG', 'Bishan', 'bishan-sg', true, 220),
  ('Singapore', 'SG', 'Marine Parade', 'marine-parade-sg', true, 230),
  ('Singapore', 'SG', 'Bukit Panjang', 'bukit-panjang-sg', true, 240),
  ('Singapore', 'SG', 'Sembawang', 'sembawang-sg', true, 250),
  ('Singapore', 'SG', 'Tengah', 'tengah-sg', true, 260),
  ('Singapore', 'SG', 'Downtown Core', 'downtown-core-sg', true, 270),
  ('Singapore', 'SG', 'Orchard', 'orchard-sg', true, 280),
  ('Singapore', 'SG', 'Marina Bay', 'marina-bay-sg', true, 290),
  ('Singapore', 'SG', 'Changi', 'changi-sg', true, 300),
  ('Singapore', 'SG', 'Jurong West', 'jurong-west-sg', true, 310),
  ('Singapore', 'SG', 'Pioneer', 'pioneer-sg', true, 320),
  ('Singapore', 'SG', 'Boon Lay', 'boon-lay-sg', true, 330),
  ('Singapore', 'SG', 'Tuas', 'tuas-sg', true, 340),
  ('Singapore', 'SG', 'Mandai', 'mandai-sg', true, 350),
  ('Singapore', 'SG', 'Seletar', 'seletar-sg', true, 360),
  ('Singapore', 'SG', 'Paya Lebar', 'paya-lebar-sg', true, 370),
  ('Singapore', 'SG', 'Eunos', 'eunos-sg', true, 380),
  ('Singapore', 'SG', 'Kembangan', 'kembangan-sg', true, 390),
  ('Singapore', 'SG', 'Siglap', 'siglap-sg', true, 400),
  ('United Arab Emirates', 'AE', 'Dubai', 'dubai-ae', true, 10),
  ('United Arab Emirates', 'AE', 'Abu Dhabi', 'abu-dhabi-ae', true, 20),
  ('United Arab Emirates', 'AE', 'Sharjah', 'sharjah-ae', true, 30),
  ('United Arab Emirates', 'AE', 'Al Ain', 'al-ain-ae', true, 40),
  ('United Arab Emirates', 'AE', 'Ajman', 'ajman-ae', true, 50),
  ('United Arab Emirates', 'AE', 'Ras Al Khaimah', 'ras-al-khaimah-ae', true, 60),
  ('United Arab Emirates', 'AE', 'Fujairah', 'fujairah-ae', true, 70),
  ('United Arab Emirates', 'AE', 'Umm Al Quwain', 'umm-al-quwain-ae', true, 80),
  ('United Arab Emirates', 'AE', 'Khor Fakkan', 'khor-fakkan-ae', true, 90),
  ('United Arab Emirates', 'AE', 'Kalba', 'kalba-ae', true, 100),
  ('United Arab Emirates', 'AE', 'Dibba Al Fujairah', 'dibba-al-fujairah-ae', true, 110),
  ('United Arab Emirates', 'AE', 'Dibba Al Hisn', 'dibba-al-hisn-ae', true, 120),
  ('United Arab Emirates', 'AE', 'Hatta', 'hatta-ae', true, 130),
  ('United Arab Emirates', 'AE', 'Madinat Zayed', 'madinat-zayed-ae', true, 140),
  ('United Arab Emirates', 'AE', 'Ruwais', 'ruwais-ae', true, 150),
  ('United Arab Emirates', 'AE', 'Ghayathi', 'ghayathi-ae', true, 160),
  ('United Arab Emirates', 'AE', 'Liwa', 'liwa-ae', true, 170),
  ('United Arab Emirates', 'AE', 'Jebel Ali', 'jebel-ali-ae', true, 180),
  ('United Arab Emirates', 'AE', 'Deira', 'deira-ae', true, 190),
  ('United Arab Emirates', 'AE', 'Bur Dubai', 'bur-dubai-ae', true, 200),
  ('United Arab Emirates', 'AE', 'Palm Jumeirah', 'palm-jumeirah-ae', true, 210),
  ('United Arab Emirates', 'AE', 'Dubai Marina', 'dubai-marina-ae', true, 220),
  ('United Arab Emirates', 'AE', 'Downtown Dubai', 'downtown-dubai-ae', true, 230),
  ('United Arab Emirates', 'AE', 'Al Barsha', 'al-barsha-ae', true, 240),
  ('United Arab Emirates', 'AE', 'Al Nahda', 'al-nahda-ae', true, 250),
  ('United Arab Emirates', 'AE', 'Al Qusais', 'al-qusais-ae', true, 260),
  ('United Arab Emirates', 'AE', 'Mirdif', 'mirdif-ae', true, 270),
  ('United Arab Emirates', 'AE', 'Silicon Oasis', 'silicon-oasis-ae', true, 280),
  ('United Arab Emirates', 'AE', 'Dubai Hills', 'dubai-hills-ae', true, 290),
  ('United Arab Emirates', 'AE', 'Arabian Ranches', 'arabian-ranches-ae', true, 300),
  ('United Arab Emirates', 'AE', 'Yas Island', 'yas-island-ae', true, 310),
  ('United Arab Emirates', 'AE', 'Saadiyat Island', 'saadiyat-island-ae', true, 320),
  ('United Arab Emirates', 'AE', 'Al Reem Island', 'al-reem-island-ae', true, 330),
  ('United Arab Emirates', 'AE', 'Khalifa City', 'khalifa-city-ae', true, 340),
  ('United Arab Emirates', 'AE', 'Mohammed Bin Zayed City', 'mohammed-bin-zayed-city-ae', true, 350),
  ('United Arab Emirates', 'AE', 'Al Zahia', 'al-zahia-ae', true, 360),
  ('United Arab Emirates', 'AE', 'Muwaileh', 'muwaileh-ae', true, 370),
  ('United Arab Emirates', 'AE', 'Al Khan', 'al-khan-ae', true, 380),
  ('United Arab Emirates', 'AE', 'Al Majaz', 'al-majaz-ae', true, 390),
  ('United Arab Emirates', 'AE', 'Al Taawun', 'al-taawun-ae', true, 400),
  ('Argentina', 'AR', 'Buenos Aires', 'buenos-aires-ar', true, 10),
  ('Argentina', 'AR', 'Cordoba', 'cordoba-ar', true, 20),
  ('Argentina', 'AR', 'Rosario', 'rosario-ar', true, 30),
  ('Argentina', 'AR', 'Mendoza', 'mendoza-ar', true, 40),
  ('Argentina', 'AR', 'La Plata', 'la-plata-ar', true, 50),
  ('Argentina', 'AR', 'Mar del Plata', 'mar-del-plata-ar', true, 60),
  ('Argentina', 'AR', 'San Miguel de Tucuman', 'san-miguel-de-tucuman-ar', true, 70),
  ('Argentina', 'AR', 'Salta', 'salta-ar', true, 80),
  ('Argentina', 'AR', 'Santa Fe', 'santa-fe-ar', true, 90),
  ('Argentina', 'AR', 'San Juan', 'san-juan-ar', true, 100),
  ('Argentina', 'AR', 'Resistencia', 'resistencia-ar', true, 110),
  ('Argentina', 'AR', 'Neuquen', 'neuquen-ar', true, 120),
  ('Argentina', 'AR', 'Santiago del Estero', 'santiago-del-estero-ar', true, 130),
  ('Argentina', 'AR', 'Corrientes', 'corrientes-ar', true, 140),
  ('Argentina', 'AR', 'Bahia Blanca', 'bahia-blanca-ar', true, 150),
  ('Argentina', 'AR', 'Posadas', 'posadas-ar', true, 160),
  ('Argentina', 'AR', 'San Salvador de Jujuy', 'san-salvador-de-jujuy-ar', true, 170),
  ('Argentina', 'AR', 'Parana', 'parana-ar', true, 180),
  ('Argentina', 'AR', 'Formosa', 'formosa-ar', true, 190),
  ('Argentina', 'AR', 'San Luis', 'san-luis-ar', true, 200),
  ('Argentina', 'AR', 'San Rafael', 'san-rafael-ar', true, 210),
  ('Argentina', 'AR', 'Comodoro Rivadavia', 'comodoro-rivadavia-ar', true, 220),
  ('Argentina', 'AR', 'Rio Cuarto', 'rio-cuarto-ar', true, 230),
  ('Argentina', 'AR', 'Concordia', 'concordia-ar', true, 240),
  ('Argentina', 'AR', 'San Nicolas', 'san-nicolas-ar', true, 250),
  ('Argentina', 'AR', 'Villa Maria', 'villa-maria-ar', true, 260),
  ('Argentina', 'AR', 'San Fernando del Valle de Catamarca', 'san-fernando-del-valle-de-catamarca-ar', true, 270),
  ('Argentina', 'AR', 'Trelew', 'trelew-ar', true, 280),
  ('Argentina', 'AR', 'Rio Gallegos', 'rio-gallegos-ar', true, 290),
  ('Argentina', 'AR', 'Ushuaia', 'ushuaia-ar', true, 300),
  ('Argentina', 'AR', 'San Carlos de Bariloche', 'san-carlos-de-bariloche-ar', true, 310),
  ('Argentina', 'AR', 'Villa Carlos Paz', 'villa-carlos-paz-ar', true, 320),
  ('Argentina', 'AR', 'Zarate', 'zarate-ar', true, 330),
  ('Argentina', 'AR', 'La Rioja', 'la-rioja-ar', true, 340),
  ('Argentina', 'AR', 'Rawson', 'rawson-ar', true, 350),
  ('Argentina', 'AR', 'Viedma', 'viedma-ar', true, 360),
  ('Argentina', 'AR', 'Obera', 'obera-ar', true, 370),
  ('Argentina', 'AR', 'Gualeguaychu', 'gualeguaychu-ar', true, 380),
  ('Argentina', 'AR', 'Venado Tuerto', 'venado-tuerto-ar', true, 390),
  ('Argentina', 'AR', 'Pilar', 'pilar-ar', true, 400),
  ('Mexico', 'MX', 'Ciudad de Mexico', 'ciudad-de-mexico-mx', true, 10),
  ('Mexico', 'MX', 'Guadalajara', 'guadalajara-mx', true, 20),
  ('Mexico', 'MX', 'Monterrey', 'monterrey-mx', true, 30),
  ('Mexico', 'MX', 'Cancun', 'cancun-mx', true, 40),
  ('Mexico', 'MX', 'Puebla', 'puebla-mx', true, 50),
  ('Mexico', 'MX', 'Tijuana', 'tijuana-mx', true, 60),
  ('Mexico', 'MX', 'Leon', 'leon-mx', true, 70),
  ('Mexico', 'MX', 'Juarez', 'juarez-mx', true, 80),
  ('Mexico', 'MX', 'Zapopan', 'zapopan-mx', true, 90),
  ('Mexico', 'MX', 'Merida', 'merida-mx', true, 100),
  ('Mexico', 'MX', 'San Luis Potosi', 'san-luis-potosi-mx', true, 110),
  ('Mexico', 'MX', 'Aguascalientes', 'aguascalientes-mx', true, 120),
  ('Mexico', 'MX', 'Hermosillo', 'hermosillo-mx', true, 130),
  ('Mexico', 'MX', 'Saltillo', 'saltillo-mx', true, 140),
  ('Mexico', 'MX', 'Mexicali', 'mexicali-mx', true, 150),
  ('Mexico', 'MX', 'Culiacan', 'culiacan-mx', true, 160),
  ('Mexico', 'MX', 'Acapulco', 'acapulco-mx', true, 170),
  ('Mexico', 'MX', 'Queretaro', 'queretaro-mx', true, 180),
  ('Mexico', 'MX', 'Torreon', 'torreon-mx', true, 190),
  ('Mexico', 'MX', 'Chihuahua', 'chihuahua-mx', true, 200),
  ('Mexico', 'MX', 'Morelia', 'morelia-mx', true, 210),
  ('Mexico', 'MX', 'Reynosa', 'reynosa-mx', true, 220),
  ('Mexico', 'MX', 'Tampico', 'tampico-mx', true, 230),
  ('Mexico', 'MX', 'Toluca', 'toluca-mx', true, 240),
  ('Mexico', 'MX', 'Cuernavaca', 'cuernavaca-mx', true, 250),
  ('Mexico', 'MX', 'Veracruz', 'veracruz-mx', true, 260),
  ('Mexico', 'MX', 'Xalapa', 'xalapa-mx', true, 270),
  ('Mexico', 'MX', 'Oaxaca', 'oaxaca-mx', true, 280),
  ('Mexico', 'MX', 'Tuxtla Gutierrez', 'tuxtla-gutierrez-mx', true, 290),
  ('Mexico', 'MX', 'Villahermosa', 'villahermosa-mx', true, 300),
  ('Mexico', 'MX', 'Durango', 'durango-mx', true, 310),
  ('Mexico', 'MX', 'Tepic', 'tepic-mx', true, 320),
  ('Mexico', 'MX', 'Campeche', 'campeche-mx', true, 330),
  ('Mexico', 'MX', 'Chetumal', 'chetumal-mx', true, 340),
  ('Mexico', 'MX', 'La Paz', 'la-paz-mx', true, 350),
  ('Mexico', 'MX', 'Cabo San Lucas', 'cabo-san-lucas-mx', true, 360),
  ('Mexico', 'MX', 'Puerto Vallarta', 'puerto-vallarta-mx', true, 370),
  ('Mexico', 'MX', 'Playa del Carmen', 'playa-del-carmen-mx', true, 380),
  ('Mexico', 'MX', 'Pachuca', 'pachuca-mx', true, 390),
  ('Mexico', 'MX', 'Celaya', 'celaya-mx', true, 400),
  ('Peru', 'PE', 'Lima', 'lima-pe', true, 10),
  ('Peru', 'PE', 'Arequipa', 'arequipa-pe', true, 20),
  ('Peru', 'PE', 'Trujillo', 'trujillo-pe', true, 30),
  ('Peru', 'PE', 'Chiclayo', 'chiclayo-pe', true, 40),
  ('Peru', 'PE', 'Piura', 'piura-pe', true, 50),
  ('Peru', 'PE', 'Iquitos', 'iquitos-pe', true, 60),
  ('Peru', 'PE', 'Cusco', 'cusco-pe', true, 70),
  ('Peru', 'PE', 'Huancayo', 'huancayo-pe', true, 80),
  ('Peru', 'PE', 'Chimbote', 'chimbote-pe', true, 90),
  ('Peru', 'PE', 'Pucallpa', 'pucallpa-pe', true, 100),
  ('Peru', 'PE', 'Tacna', 'tacna-pe', true, 110),
  ('Peru', 'PE', 'Ica', 'ica-pe', true, 120),
  ('Peru', 'PE', 'Juliaca', 'juliaca-pe', true, 130),
  ('Peru', 'PE', 'Sullana', 'sullana-pe', true, 140),
  ('Peru', 'PE', 'Cajamarca', 'cajamarca-pe', true, 150),
  ('Peru', 'PE', 'Ayacucho', 'ayacucho-pe', true, 160),
  ('Peru', 'PE', 'Chincha Alta', 'chincha-alta-pe', true, 170),
  ('Peru', 'PE', 'Huanuco', 'huanuco-pe', true, 180),
  ('Peru', 'PE', 'Puno', 'puno-pe', true, 190),
  ('Peru', 'PE', 'Tarapoto', 'tarapoto-pe', true, 200),
  ('Peru', 'PE', 'Pisco', 'pisco-pe', true, 210),
  ('Peru', 'PE', 'Huaraz', 'huaraz-pe', true, 220),
  ('Peru', 'PE', 'Tumbes', 'tumbes-pe', true, 230),
  ('Peru', 'PE', 'Talara', 'talara-pe', true, 240),
  ('Peru', 'PE', 'Jaen', 'jaen-pe', true, 250),
  ('Peru', 'PE', 'Moyobamba', 'moyobamba-pe', true, 260),
  ('Peru', 'PE', 'Puerto Maldonado', 'puerto-maldonado-pe', true, 270),
  ('Peru', 'PE', 'Abancay', 'abancay-pe', true, 280),
  ('Peru', 'PE', 'Moquegua', 'moquegua-pe', true, 290),
  ('Peru', 'PE', 'Ilo', 'ilo-pe', true, 300),
  ('Peru', 'PE', 'Nasca', 'nasca-pe', true, 310),
  ('Peru', 'PE', 'Barranca', 'barranca-pe', true, 320),
  ('Peru', 'PE', 'Huacho', 'huacho-pe', true, 330),
  ('Peru', 'PE', 'Chancay', 'chancay-pe', true, 340),
  ('Peru', 'PE', 'Cañete', 'canete-pe', true, 350),
  ('Peru', 'PE', 'Cerro de Pasco', 'cerro-de-pasco-pe', true, 360),
  ('Peru', 'PE', 'Tingo Maria', 'tingo-maria-pe', true, 370),
  ('Peru', 'PE', 'Yurimaguas', 'yurimaguas-pe', true, 380),
  ('Peru', 'PE', 'Chachapoyas', 'chachapoyas-pe', true, 390),
  ('Peru', 'PE', 'Huancavelica', 'huancavelica-pe', true, 400),
  ('Costa Rica', 'CR', 'San Jose', 'san-jose-cr', true, 10),
  ('Costa Rica', 'CR', 'Alajuela', 'alajuela-cr', true, 20),
  ('Costa Rica', 'CR', 'Cartago', 'cartago-cr', true, 30),
  ('Costa Rica', 'CR', 'Heredia', 'heredia-cr', true, 40),
  ('Costa Rica', 'CR', 'Liberia', 'liberia-cr', true, 50),
  ('Costa Rica', 'CR', 'Puntarenas', 'puntarenas-cr', true, 60),
  ('Costa Rica', 'CR', 'Limon', 'limon-cr', true, 70),
  ('Costa Rica', 'CR', 'San Francisco', 'san-francisco-cr', true, 80),
  ('Costa Rica', 'CR', 'Desamparados', 'desamparados-cr', true, 90),
  ('Costa Rica', 'CR', 'Curridabat', 'curridabat-cr', true, 100),
  ('Costa Rica', 'CR', 'Tibas', 'tibas-cr', true, 110),
  ('Costa Rica', 'CR', 'Goicoechea', 'goicoechea-cr', true, 120),
  ('Costa Rica', 'CR', 'Perez Zeledon', 'perez-zeledon-cr', true, 130),
  ('Costa Rica', 'CR', 'Grecia', 'grecia-cr', true, 140),
  ('Costa Rica', 'CR', 'San Ramon', 'san-ramon-cr', true, 150),
  ('Costa Rica', 'CR', 'Quesada', 'quesada-cr', true, 160),
  ('Costa Rica', 'CR', 'Pital', 'pital-cr', true, 170),
  ('Costa Rica', 'CR', 'Guapiles', 'guapiles-cr', true, 180),
  ('Costa Rica', 'CR', 'Turrialba', 'turrialba-cr', true, 190),
  ('Costa Rica', 'CR', 'Escazu', 'escazu-cr', true, 200),
  ('Costa Rica', 'CR', 'Santa Ana', 'santa-ana-cr', true, 210),
  ('Costa Rica', 'CR', 'Belén', 'belen-cr', true, 220),
  ('Costa Rica', 'CR', 'Nicoya', 'nicoya-cr', true, 230),
  ('Costa Rica', 'CR', 'Cañas', 'canas-cr', true, 240),
  ('Costa Rica', 'CR', 'Santa Cruz', 'santa-cruz-cr', true, 250),
  ('Costa Rica', 'CR', 'Quepos', 'quepos-cr', true, 260),
  ('Costa Rica', 'CR', 'Golfito', 'golfito-cr', true, 270),
  ('Costa Rica', 'CR', 'San Isidro', 'san-isidro-cr', true, 280),
  ('Costa Rica', 'CR', 'Palmares', 'palmares-cr', true, 290),
  ('Costa Rica', 'CR', 'Naranjo', 'naranjo-cr', true, 300),
  ('Costa Rica', 'CR', 'Orotina', 'orotina-cr', true, 310),
  ('Costa Rica', 'CR', 'Atenas', 'atenas-cr', true, 320),
  ('Costa Rica', 'CR', 'Puriscal', 'puriscal-cr', true, 330),
  ('Costa Rica', 'CR', 'Siquirres', 'siquirres-cr', true, 340),
  ('Costa Rica', 'CR', 'Guacimo', 'guacimo-cr', true, 350),
  ('Costa Rica', 'CR', 'Paraiso', 'paraiso-cr', true, 360),
  ('Costa Rica', 'CR', 'La Union', 'la-union-cr', true, 370),
  ('Costa Rica', 'CR', 'Moravia', 'moravia-cr', true, 380),
  ('Costa Rica', 'CR', 'Montes de Oca', 'montes-de-oca-cr', true, 390),
  ('Costa Rica', 'CR', 'Coronado', 'coronado-cr', true, 400),
  ('Brazil', 'BR', 'Sao Paulo', 'sao-paulo-br', true, 10),
  ('Brazil', 'BR', 'Rio de Janeiro', 'rio-de-janeiro-br', true, 20),
  ('Brazil', 'BR', 'Brasilia', 'brasilia-br', true, 30),
  ('Brazil', 'BR', 'Salvador', 'salvador-br', true, 40),
  ('Brazil', 'BR', 'Fortaleza', 'fortaleza-br', true, 50),
  ('Brazil', 'BR', 'Belo Horizonte', 'belo-horizonte-br', true, 60),
  ('Brazil', 'BR', 'Manaus', 'manaus-br', true, 70),
  ('Brazil', 'BR', 'Curitiba', 'curitiba-br', true, 80),
  ('Brazil', 'BR', 'Recife', 'recife-br', true, 90),
  ('Brazil', 'BR', 'Goiania', 'goiania-br', true, 100),
  ('Brazil', 'BR', 'Belem', 'belem-br', true, 110),
  ('Brazil', 'BR', 'Porto Alegre', 'porto-alegre-br', true, 120),
  ('Brazil', 'BR', 'Guarulhos', 'guarulhos-br', true, 130),
  ('Brazil', 'BR', 'Campinas', 'campinas-br', true, 140),
  ('Brazil', 'BR', 'Sao Luis', 'sao-luis-br', true, 150),
  ('Brazil', 'BR', 'Maceio', 'maceio-br', true, 160),
  ('Brazil', 'BR', 'Campo Grande', 'campo-grande-br', true, 170),
  ('Brazil', 'BR', 'Natal', 'natal-br', true, 180),
  ('Brazil', 'BR', 'Teresina', 'teresina-br', true, 190),
  ('Brazil', 'BR', 'Sao Bernardo do Campo', 'sao-bernardo-do-campo-br', true, 200),
  ('Brazil', 'BR', 'Joao Pessoa', 'joao-pessoa-br', true, 210),
  ('Brazil', 'BR', 'Santo Andre', 'santo-andre-br', true, 220),
  ('Brazil', 'BR', 'Osasco', 'osasco-br', true, 230),
  ('Brazil', 'BR', 'Ribeirao Preto', 'ribeirao-preto-br', true, 240),
  ('Brazil', 'BR', 'Uberlandia', 'uberlandia-br', true, 250),
  ('Brazil', 'BR', 'Sorocaba', 'sorocaba-br', true, 260),
  ('Brazil', 'BR', 'Cuiaba', 'cuiaba-br', true, 270),
  ('Brazil', 'BR', 'Aracaju', 'aracaju-br', true, 280),
  ('Brazil', 'BR', 'Feira de Santana', 'feira-de-santana-br', true, 290),
  ('Brazil', 'BR', 'Joinville', 'joinville-br', true, 300),
  ('Brazil', 'BR', 'Juiz de Fora', 'juiz-de-fora-br', true, 310),
  ('Brazil', 'BR', 'Londrina', 'londrina-br', true, 320),
  ('Brazil', 'BR', 'Niteroi', 'niteroi-br', true, 330),
  ('Brazil', 'BR', 'Florianopolis', 'florianopolis-br', true, 340),
  ('Brazil', 'BR', 'Santos', 'santos-br', true, 350),
  ('Brazil', 'BR', 'Vila Velha', 'vila-velha-br', true, 360),
  ('Brazil', 'BR', 'Serra', 'serra-br', true, 370),
  ('Brazil', 'BR', 'Caxias do Sul', 'caxias-do-sul-br', true, 380),
  ('Brazil', 'BR', 'Campos dos Goytacazes', 'campos-dos-goytacazes-br', true, 390),
  ('Brazil', 'BR', 'Macapa', 'macapa-br', true, 400),
  ('Spain', 'ES', 'Madrid', 'madrid-es', true, 10),
  ('Spain', 'ES', 'Barcelona', 'barcelona-es', true, 20),
  ('Spain', 'ES', 'Valencia', 'valencia-es', true, 30),
  ('Spain', 'ES', 'Sevilla', 'sevilla-es', true, 40),
  ('Spain', 'ES', 'Zaragoza', 'zaragoza-es', true, 50),
  ('Spain', 'ES', 'Malaga', 'malaga-es', true, 60),
  ('Spain', 'ES', 'Murcia', 'murcia-es', true, 70),
  ('Spain', 'ES', 'Palma', 'palma-es', true, 80),
  ('Spain', 'ES', 'Las Palmas', 'las-palmas-es', true, 90),
  ('Spain', 'ES', 'Bilbao', 'bilbao-es', true, 100),
  ('Spain', 'ES', 'Alicante', 'alicante-es', true, 110),
  ('Spain', 'ES', 'Cordoba', 'cordoba-es', true, 120),
  ('Spain', 'ES', 'Valladolid', 'valladolid-es', true, 130),
  ('Spain', 'ES', 'Vigo', 'vigo-es', true, 140),
  ('Spain', 'ES', 'Gijon', 'gijon-es', true, 150),
  ('Spain', 'ES', 'Hospitalet', 'hospitalet-es', true, 160),
  ('Spain', 'ES', 'Vitoria', 'vitoria-es', true, 170),
  ('Spain', 'ES', 'A Coruna', 'a-coruna-es', true, 180),
  ('Spain', 'ES', 'Granada', 'granada-es', true, 190),
  ('Spain', 'ES', 'Elche', 'elche-es', true, 200),
  ('Spain', 'ES', 'Oviedo', 'oviedo-es', true, 210),
  ('Spain', 'ES', 'Badalona', 'badalona-es', true, 220),
  ('Spain', 'ES', 'Terrassa', 'terrassa-es', true, 230),
  ('Spain', 'ES', 'Sabadell', 'sabadell-es', true, 240),
  ('Spain', 'ES', 'Cartagena', 'cartagena-es', true, 250),
  ('Spain', 'ES', 'Jerez', 'jerez-es', true, 260),
  ('Spain', 'ES', 'Santa Cruz de Tenerife', 'santa-cruz-de-tenerife-es', true, 270),
  ('Spain', 'ES', 'Pamplona', 'pamplona-es', true, 280),
  ('Spain', 'ES', 'Almeria', 'almeria-es', true, 290),
  ('Spain', 'ES', 'San Sebastian', 'san-sebastian-es', true, 300),
  ('Spain', 'ES', 'Burgos', 'burgos-es', true, 310),
  ('Spain', 'ES', 'Albacete', 'albacete-es', true, 320),
  ('Spain', 'ES', 'Santander', 'santander-es', true, 330),
  ('Spain', 'ES', 'Castellon', 'castellon-es', true, 340),
  ('Spain', 'ES', 'Logrono', 'logrono-es', true, 350),
  ('Spain', 'ES', 'Badajoz', 'badajoz-es', true, 360),
  ('Spain', 'ES', 'Salamanca', 'salamanca-es', true, 370),
  ('Spain', 'ES', 'Huelva', 'huelva-es', true, 380),
  ('Spain', 'ES', 'Lleida', 'lleida-es', true, 390),
  ('Spain', 'ES', 'Tarragona', 'tarragona-es', true, 400),
  ('United Kingdom', 'GB', 'London', 'london-gb', true, 10),
  ('United Kingdom', 'GB', 'Birmingham', 'birmingham-gb', true, 20),
  ('United Kingdom', 'GB', 'Manchester', 'manchester-gb', true, 30),
  ('United Kingdom', 'GB', 'Glasgow', 'glasgow-gb', true, 40),
  ('United Kingdom', 'GB', 'Liverpool', 'liverpool-gb', true, 50),
  ('United Kingdom', 'GB', 'Bristol', 'bristol-gb', true, 60),
  ('United Kingdom', 'GB', 'Leeds', 'leeds-gb', true, 70),
  ('United Kingdom', 'GB', 'Sheffield', 'sheffield-gb', true, 80),
  ('United Kingdom', 'GB', 'Edinburgh', 'edinburgh-gb', true, 90),
  ('United Kingdom', 'GB', 'Leicester', 'leicester-gb', true, 100),
  ('United Kingdom', 'GB', 'Coventry', 'coventry-gb', true, 110),
  ('United Kingdom', 'GB', 'Bradford', 'bradford-gb', true, 120),
  ('United Kingdom', 'GB', 'Cardiff', 'cardiff-gb', true, 130),
  ('United Kingdom', 'GB', 'Belfast', 'belfast-gb', true, 140),
  ('United Kingdom', 'GB', 'Nottingham', 'nottingham-gb', true, 150),
  ('United Kingdom', 'GB', 'Kingston upon Hull', 'kingston-upon-hull-gb', true, 160),
  ('United Kingdom', 'GB', 'Newcastle', 'newcastle-gb', true, 170),
  ('United Kingdom', 'GB', 'Stoke-on-Trent', 'stoke-on-trent-gb', true, 180),
  ('United Kingdom', 'GB', 'Southampton', 'southampton-gb', true, 190),
  ('United Kingdom', 'GB', 'Derby', 'derby-gb', true, 200),
  ('United Kingdom', 'GB', 'Portsmouth', 'portsmouth-gb', true, 210),
  ('United Kingdom', 'GB', 'Brighton', 'brighton-gb', true, 220),
  ('United Kingdom', 'GB', 'Plymouth', 'plymouth-gb', true, 230),
  ('United Kingdom', 'GB', 'Northampton', 'northampton-gb', true, 240),
  ('United Kingdom', 'GB', 'Reading', 'reading-gb', true, 250),
  ('United Kingdom', 'GB', 'Luton', 'luton-gb', true, 260),
  ('United Kingdom', 'GB', 'Wolverhampton', 'wolverhampton-gb', true, 270),
  ('United Kingdom', 'GB', 'Bolton', 'bolton-gb', true, 280),
  ('United Kingdom', 'GB', 'Aberdeen', 'aberdeen-gb', true, 290),
  ('United Kingdom', 'GB', 'Bournemouth', 'bournemouth-gb', true, 300),
  ('United Kingdom', 'GB', 'Norwich', 'norwich-gb', true, 310),
  ('United Kingdom', 'GB', 'Swindon', 'swindon-gb', true, 320),
  ('United Kingdom', 'GB', 'Swansea', 'swansea-gb', true, 330),
  ('United Kingdom', 'GB', 'Milton Keynes', 'milton-keynes-gb', true, 340),
  ('United Kingdom', 'GB', 'Southend', 'southend-gb', true, 350),
  ('United Kingdom', 'GB', 'Middlesbrough', 'middlesbrough-gb', true, 360),
  ('United Kingdom', 'GB', 'Peterborough', 'peterborough-gb', true, 370),
  ('United Kingdom', 'GB', 'Oxford', 'oxford-gb', true, 380),
  ('United Kingdom', 'GB', 'Cambridge', 'cambridge-gb', true, 390),
  ('United Kingdom', 'GB', 'York', 'york-gb', true, 400),
  ('Germany', 'DE', 'Berlin', 'berlin-de', true, 10),
  ('Germany', 'DE', 'Hamburg', 'hamburg-de', true, 20),
  ('Germany', 'DE', 'Munich', 'munich-de', true, 30),
  ('Germany', 'DE', 'Cologne', 'cologne-de', true, 40),
  ('Germany', 'DE', 'Frankfurt', 'frankfurt-de', true, 50),
  ('Germany', 'DE', 'Stuttgart', 'stuttgart-de', true, 60),
  ('Germany', 'DE', 'Dusseldorf', 'dusseldorf-de', true, 70),
  ('Germany', 'DE', 'Leipzig', 'leipzig-de', true, 80),
  ('Germany', 'DE', 'Dortmund', 'dortmund-de', true, 90),
  ('Germany', 'DE', 'Essen', 'essen-de', true, 100),
  ('Germany', 'DE', 'Bremen', 'bremen-de', true, 110),
  ('Germany', 'DE', 'Dresden', 'dresden-de', true, 120),
  ('Germany', 'DE', 'Hanover', 'hanover-de', true, 130),
  ('Germany', 'DE', 'Nuremberg', 'nuremberg-de', true, 140),
  ('Germany', 'DE', 'Duisburg', 'duisburg-de', true, 150),
  ('Germany', 'DE', 'Bochum', 'bochum-de', true, 160),
  ('Germany', 'DE', 'Wuppertal', 'wuppertal-de', true, 170),
  ('Germany', 'DE', 'Bielefeld', 'bielefeld-de', true, 180),
  ('Germany', 'DE', 'Bonn', 'bonn-de', true, 190),
  ('Germany', 'DE', 'Munster', 'munster-de', true, 200),
  ('Germany', 'DE', 'Karlsruhe', 'karlsruhe-de', true, 210),
  ('Germany', 'DE', 'Mannheim', 'mannheim-de', true, 220),
  ('Germany', 'DE', 'Augsburg', 'augsburg-de', true, 230),
  ('Germany', 'DE', 'Wiesbaden', 'wiesbaden-de', true, 240),
  ('Germany', 'DE', 'Gelsenkirchen', 'gelsenkirchen-de', true, 250),
  ('Germany', 'DE', 'Moenchengladbach', 'moenchengladbach-de', true, 260),
  ('Germany', 'DE', 'Braunschweig', 'braunschweig-de', true, 270),
  ('Germany', 'DE', 'Chemnitz', 'chemnitz-de', true, 280),
  ('Germany', 'DE', 'Kiel', 'kiel-de', true, 290),
  ('Germany', 'DE', 'Aachen', 'aachen-de', true, 300),
  ('Germany', 'DE', 'Halle', 'halle-de', true, 310),
  ('Germany', 'DE', 'Magdeburg', 'magdeburg-de', true, 320),
  ('Germany', 'DE', 'Freiburg', 'freiburg-de', true, 330),
  ('Germany', 'DE', 'Krefeld', 'krefeld-de', true, 340),
  ('Germany', 'DE', 'Luebeck', 'luebeck-de', true, 350),
  ('Germany', 'DE', 'Oberhausen', 'oberhausen-de', true, 360),
  ('Germany', 'DE', 'Erfurt', 'erfurt-de', true, 370),
  ('Germany', 'DE', 'Mainz', 'mainz-de', true, 380),
  ('Germany', 'DE', 'Rostock', 'rostock-de', true, 390),
  ('Germany', 'DE', 'Kassel', 'kassel-de', true, 400),
  ('France', 'FR', 'Paris', 'paris-fr', true, 10),
  ('France', 'FR', 'Marseille', 'marseille-fr', true, 20),
  ('France', 'FR', 'Lyon', 'lyon-fr', true, 30),
  ('France', 'FR', 'Toulouse', 'toulouse-fr', true, 40),
  ('France', 'FR', 'Nice', 'nice-fr', true, 50),
  ('France', 'FR', 'Nantes', 'nantes-fr', true, 60),
  ('France', 'FR', 'Montpellier', 'montpellier-fr', true, 70),
  ('France', 'FR', 'Strasbourg', 'strasbourg-fr', true, 80),
  ('France', 'FR', 'Bordeaux', 'bordeaux-fr', true, 90),
  ('France', 'FR', 'Lille', 'lille-fr', true, 100),
  ('France', 'FR', 'Rennes', 'rennes-fr', true, 110),
  ('France', 'FR', 'Reims', 'reims-fr', true, 120),
  ('France', 'FR', 'Saint-Etienne', 'saint-etienne-fr', true, 130),
  ('France', 'FR', 'Toulon', 'toulon-fr', true, 140),
  ('France', 'FR', 'Le Havre', 'le-havre-fr', true, 150),
  ('France', 'FR', 'Grenoble', 'grenoble-fr', true, 160),
  ('France', 'FR', 'Dijon', 'dijon-fr', true, 170),
  ('France', 'FR', 'Angers', 'angers-fr', true, 180),
  ('France', 'FR', 'Villeurbanne', 'villeurbanne-fr', true, 190),
  ('France', 'FR', 'Nimes', 'nimes-fr', true, 200),
  ('France', 'FR', 'Aix-en-Provence', 'aix-en-provence-fr', true, 210),
  ('France', 'FR', 'Clermont-Ferrand', 'clermont-ferrand-fr', true, 220),
  ('France', 'FR', 'Le Mans', 'le-mans-fr', true, 230),
  ('France', 'FR', 'Brest', 'brest-fr', true, 240),
  ('France', 'FR', 'Tours', 'tours-fr', true, 250),
  ('France', 'FR', 'Amiens', 'amiens-fr', true, 260),
  ('France', 'FR', 'Limoges', 'limoges-fr', true, 270),
  ('France', 'FR', 'Annecy', 'annecy-fr', true, 280),
  ('France', 'FR', 'Perpignan', 'perpignan-fr', true, 290),
  ('France', 'FR', 'Boulogne-Billancourt', 'boulogne-billancourt-fr', true, 300),
  ('France', 'FR', 'Metz', 'metz-fr', true, 310),
  ('France', 'FR', 'Besancon', 'besancon-fr', true, 320),
  ('France', 'FR', 'Orleans', 'orleans-fr', true, 330),
  ('France', 'FR', 'Saint-Denis', 'saint-denis-fr', true, 340),
  ('France', 'FR', 'Rouen', 'rouen-fr', true, 350),
  ('France', 'FR', 'Mulhouse', 'mulhouse-fr', true, 360),
  ('France', 'FR', 'Caen', 'caen-fr', true, 370),
  ('France', 'FR', 'Nancy', 'nancy-fr', true, 380),
  ('France', 'FR', 'Argenteuil', 'argenteuil-fr', true, 390),
  ('France', 'FR', 'Montreuil', 'montreuil-fr', true, 400),
  ('Netherlands', 'NL', 'Amsterdam', 'amsterdam-nl', true, 10),
  ('Netherlands', 'NL', 'Rotterdam', 'rotterdam-nl', true, 20),
  ('Netherlands', 'NL', 'The Hague', 'the-hague-nl', true, 30),
  ('Netherlands', 'NL', 'Utrecht', 'utrecht-nl', true, 40),
  ('Netherlands', 'NL', 'Eindhoven', 'eindhoven-nl', true, 50),
  ('Netherlands', 'NL', 'Groningen', 'groningen-nl', true, 60),
  ('Netherlands', 'NL', 'Tilburg', 'tilburg-nl', true, 70),
  ('Netherlands', 'NL', 'Almere', 'almere-nl', true, 80),
  ('Netherlands', 'NL', 'Breda', 'breda-nl', true, 90),
  ('Netherlands', 'NL', 'Nijmegen', 'nijmegen-nl', true, 100),
  ('Netherlands', 'NL', 'Apeldoorn', 'apeldoorn-nl', true, 110),
  ('Netherlands', 'NL', 'Haarlem', 'haarlem-nl', true, 120),
  ('Netherlands', 'NL', 'Arnhem', 'arnhem-nl', true, 130),
  ('Netherlands', 'NL', 'Enschede', 'enschede-nl', true, 140),
  ('Netherlands', 'NL', 'Amersfoort', 'amersfoort-nl', true, 150),
  ('Netherlands', 'NL', 'Zaanstad', 'zaanstad-nl', true, 160),
  ('Netherlands', 'NL', 'Haarlemmermeer', 'haarlemmermeer-nl', true, 170),
  ('Netherlands', 'NL', 's-Hertogenbosch', 's-hertogenbosch-nl', true, 180),
  ('Netherlands', 'NL', 'Zwolle', 'zwolle-nl', true, 190),
  ('Netherlands', 'NL', 'Zoetermeer', 'zoetermeer-nl', true, 200),
  ('Netherlands', 'NL', 'Leiden', 'leiden-nl', true, 210),
  ('Netherlands', 'NL', 'Maastricht', 'maastricht-nl', true, 220),
  ('Netherlands', 'NL', 'Dordrecht', 'dordrecht-nl', true, 230),
  ('Netherlands', 'NL', 'Ede', 'ede-nl', true, 240),
  ('Netherlands', 'NL', 'Alphen aan den Rijn', 'alphen-aan-den-rijn-nl', true, 250),
  ('Netherlands', 'NL', 'Westland', 'westland-nl', true, 260),
  ('Netherlands', 'NL', 'Alkmaar', 'alkmaar-nl', true, 270),
  ('Netherlands', 'NL', 'Emmen', 'emmen-nl', true, 280),
  ('Netherlands', 'NL', 'Delft', 'delft-nl', true, 290),
  ('Netherlands', 'NL', 'Venlo', 'venlo-nl', true, 300),
  ('Netherlands', 'NL', 'Deventer', 'deventer-nl', true, 310),
  ('Netherlands', 'NL', 'Leeuwarden', 'leeuwarden-nl', true, 320),
  ('Netherlands', 'NL', 'Helmond', 'helmond-nl', true, 330),
  ('Netherlands', 'NL', 'Hilversum', 'hilversum-nl', true, 340),
  ('Netherlands', 'NL', 'Amstelveen', 'amstelveen-nl', true, 350),
  ('Netherlands', 'NL', 'Purmerend', 'purmerend-nl', true, 360),
  ('Netherlands', 'NL', 'Hengelo', 'hengelo-nl', true, 370),
  ('Netherlands', 'NL', 'Roosendaal', 'roosendaal-nl', true, 380),
  ('Netherlands', 'NL', 'Schiedam', 'schiedam-nl', true, 390),
  ('Netherlands', 'NL', 'Lelystad', 'lelystad-nl', true, 400),
  ('India', 'IN', 'Mumbai', 'mumbai-in', true, 10),
  ('India', 'IN', 'Delhi', 'delhi-in', true, 20),
  ('India', 'IN', 'Bengaluru', 'bengaluru-in', true, 30),
  ('India', 'IN', 'Hyderabad', 'hyderabad-in', true, 40),
  ('India', 'IN', 'Ahmedabad', 'ahmedabad-in', true, 50),
  ('India', 'IN', 'Chennai', 'chennai-in', true, 60),
  ('India', 'IN', 'Kolkata', 'kolkata-in', true, 70),
  ('India', 'IN', 'Pune', 'pune-in', true, 80),
  ('India', 'IN', 'Jaipur', 'jaipur-in', true, 90),
  ('India', 'IN', 'Surat', 'surat-in', true, 100),
  ('India', 'IN', 'Lucknow', 'lucknow-in', true, 110),
  ('India', 'IN', 'Kanpur', 'kanpur-in', true, 120),
  ('India', 'IN', 'Nagpur', 'nagpur-in', true, 130),
  ('India', 'IN', 'Indore', 'indore-in', true, 140),
  ('India', 'IN', 'Thane', 'thane-in', true, 150),
  ('India', 'IN', 'Bhopal', 'bhopal-in', true, 160),
  ('India', 'IN', 'Visakhapatnam', 'visakhapatnam-in', true, 170),
  ('India', 'IN', 'Pimpri-Chinchwad', 'pimpri-chinchwad-in', true, 180),
  ('India', 'IN', 'Patna', 'patna-in', true, 190),
  ('India', 'IN', 'Vadodara', 'vadodara-in', true, 200),
  ('India', 'IN', 'Ghaziabad', 'ghaziabad-in', true, 210),
  ('India', 'IN', 'Ludhiana', 'ludhiana-in', true, 220),
  ('India', 'IN', 'Agra', 'agra-in', true, 230),
  ('India', 'IN', 'Nashik', 'nashik-in', true, 240),
  ('India', 'IN', 'Faridabad', 'faridabad-in', true, 250),
  ('India', 'IN', 'Meerut', 'meerut-in', true, 260),
  ('India', 'IN', 'Rajkot', 'rajkot-in', true, 270),
  ('India', 'IN', 'Varanasi', 'varanasi-in', true, 280),
  ('India', 'IN', 'Srinagar', 'srinagar-in', true, 290),
  ('India', 'IN', 'Aurangabad', 'aurangabad-in', true, 300),
  ('India', 'IN', 'Dhanbad', 'dhanbad-in', true, 310),
  ('India', 'IN', 'Amritsar', 'amritsar-in', true, 320),
  ('India', 'IN', 'Navi Mumbai', 'navi-mumbai-in', true, 330),
  ('India', 'IN', 'Allahabad', 'allahabad-in', true, 340),
  ('India', 'IN', 'Ranchi', 'ranchi-in', true, 350),
  ('India', 'IN', 'Howrah', 'howrah-in', true, 360),
  ('India', 'IN', 'Coimbatore', 'coimbatore-in', true, 370),
  ('India', 'IN', 'Jabalpur', 'jabalpur-in', true, 380),
  ('India', 'IN', 'Gwalior', 'gwalior-in', true, 390),
  ('India', 'IN', 'Vijayawada', 'vijayawada-in', true, 400),
  ('China', 'CN', 'Shanghai', 'shanghai-cn', true, 10),
  ('China', 'CN', 'Beijing', 'beijing-cn', true, 20),
  ('China', 'CN', 'Shenzhen', 'shenzhen-cn', true, 30),
  ('China', 'CN', 'Guangzhou', 'guangzhou-cn', true, 40),
  ('China', 'CN', 'Chengdu', 'chengdu-cn', true, 50),
  ('China', 'CN', 'Chongqing', 'chongqing-cn', true, 60),
  ('China', 'CN', 'Tianjin', 'tianjin-cn', true, 70),
  ('China', 'CN', 'Wuhan', 'wuhan-cn', true, 80),
  ('China', 'CN', 'Hangzhou', 'hangzhou-cn', true, 90),
  ('China', 'CN', 'Dongguan', 'dongguan-cn', true, 100),
  ('China', 'CN', 'Xi''an', 'xian-cn', true, 110),
  ('China', 'CN', 'Foshan', 'foshan-cn', true, 120),
  ('China', 'CN', 'Nanjing', 'nanjing-cn', true, 130),
  ('China', 'CN', 'Shenyang', 'shenyang-cn', true, 140),
  ('China', 'CN', 'Qingdao', 'qingdao-cn', true, 150),
  ('China', 'CN', 'Suzhou', 'suzhou-cn', true, 160),
  ('China', 'CN', 'Zhengzhou', 'zhengzhou-cn', true, 170),
  ('China', 'CN', 'Changsha', 'changsha-cn', true, 180),
  ('China', 'CN', 'Harbin', 'harbin-cn', true, 190),
  ('China', 'CN', 'Kunming', 'kunming-cn', true, 200),
  ('China', 'CN', 'Dalian', 'dalian-cn', true, 210),
  ('China', 'CN', 'Jinan', 'jinan-cn', true, 220),
  ('China', 'CN', 'Fuzhou', 'fuzhou-cn', true, 230),
  ('China', 'CN', 'Wuxi', 'wuxi-cn', true, 240),
  ('China', 'CN', 'Xiamen', 'xiamen-cn', true, 250),
  ('China', 'CN', 'Hefei', 'hefei-cn', true, 260),
  ('China', 'CN', 'Taiyuan', 'taiyuan-cn', true, 270),
  ('China', 'CN', 'Nanning', 'nanning-cn', true, 280),
  ('China', 'CN', 'Changchun', 'changchun-cn', true, 290),
  ('China', 'CN', 'Ningbo', 'ningbo-cn', true, 300),
  ('China', 'CN', 'Shijiazhuang', 'shijiazhuang-cn', true, 310),
  ('China', 'CN', 'Nanchang', 'nanchang-cn', true, 320),
  ('China', 'CN', 'Wenzhou', 'wenzhou-cn', true, 330),
  ('China', 'CN', 'Guiyang', 'guiyang-cn', true, 340),
  ('China', 'CN', 'Urumqi', 'urumqi-cn', true, 350),
  ('China', 'CN', 'Lanzhou', 'lanzhou-cn', true, 360),
  ('China', 'CN', 'Hohhot', 'hohhot-cn', true, 370),
  ('China', 'CN', 'Haikou', 'haikou-cn', true, 380),
  ('China', 'CN', 'Lhasa', 'lhasa-cn', true, 390),
  ('China', 'CN', 'Yinchuan', 'yinchuan-cn', true, 400)
ON CONFLICT (city_slug) DO NOTHING;
